/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.cmjd.example.com.smsccp.view.reserve;

import edu.ijse.cmjd.example.com.smsccp.serverconnector.ServerConnector;
import edu.ijse.cmjd.example.com.smsccp.controller.CustomerParkingController;
import edu.ijse.cmjd.example.com.smsccp.model.CustomerParking;
import edu.ijse.cmjd.example.com.smsccp.view.getdetail.GetDetailReserve;
import java.awt.Color;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author U s E r™
 */
public class ReservePlace extends javax.swing.JFrame {

    private boolean ifReserveSuccess;

    /**
     * Creates new form ReservePlace
     */
    public ReservePlace() {
        initComponents();
        setLocationRelativeTo(null);
        setReservPlace();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        libHome = new javax.swing.JLabel();
        p22 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p21 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p27 = new javax.swing.JLabel();
        p26 = new javax.swing.JLabel();
        p25 = new javax.swing.JLabel();
        p24 = new javax.swing.JLabel();
        p12 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p14 = new javax.swing.JLabel();
        p18 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p13 = new javax.swing.JLabel();
        p17 = new javax.swing.JLabel();
        p20 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        p16 = new javax.swing.JLabel();
        p19 = new javax.swing.JLabel();
        p11 = new javax.swing.JLabel();
        p15 = new javax.swing.JLabel();
        p23 = new javax.swing.JLabel();
        libMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(1202, 575));
        jPanel1.setPreferredSize(new java.awt.Dimension(1202, 575));
        jPanel1.setLayout(null);

        libHome.setToolTipText("Go Home");
        libHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libHomeMouseClicked(evt);
            }
        });
        jPanel1.add(libHome);
        libHome.setBounds(1150, 10, 45, 60);

        p22.setBackground(new java.awt.Color(0, 204, 102));
        p22.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p22.setForeground(new java.awt.Color(255, 255, 255));
        p22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p22.setText("Bus 22");
        p22.setToolTipText("Bus Parking Place 01");
        p22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p22.setOpaque(true);
        p22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p22MouseExited(evt);
            }
        });
        jPanel1.add(p22);
        p22.setBounds(10, 100, 170, 60);

        p4.setBackground(new java.awt.Color(0, 204, 102));
        p4.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p4.setForeground(new java.awt.Color(255, 255, 255));
        p4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p4.setText("Car 4");
        p4.setToolTipText("Car Parking Place 04");
        p4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p4.setOpaque(true);
        jPanel1.add(p4);
        p4.setBounds(1060, 100, 140, 60);

        p3.setBackground(new java.awt.Color(0, 204, 102));
        p3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p3.setForeground(new java.awt.Color(255, 255, 255));
        p3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p3.setText("Car 3");
        p3.setToolTipText("Car Parking Place 03");
        p3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p3.setOpaque(true);
        jPanel1.add(p3);
        p3.setBounds(1060, 210, 140, 60);

        p2.setBackground(new java.awt.Color(0, 204, 102));
        p2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2.setText("Car 2");
        p2.setToolTipText("Car Parking Place 02");
        p2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p2.setOpaque(true);
        jPanel1.add(p2);
        p2.setBounds(1060, 320, 140, 60);

        p1.setBackground(new java.awt.Color(0, 204, 102));
        p1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1.setText("Car 1");
        p1.setToolTipText("Car Parking Place 01");
        p1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p1.setOpaque(true);
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p1MouseExited(evt);
            }
        });
        jPanel1.add(p1);
        p1.setBounds(1060, 420, 140, 60);

        p21.setBackground(new java.awt.Color(0, 204, 102));
        p21.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p21.setForeground(new java.awt.Color(255, 255, 255));
        p21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p21.setText("Car 21");
        p21.setToolTipText("Car Parking Place 21");
        p21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p21.setOpaque(true);
        p21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p21MouseExited(evt);
            }
        });
        jPanel1.add(p21);
        p21.setBounds(310, 0, 140, 60);

        p7.setBackground(new java.awt.Color(0, 204, 102));
        p7.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p7.setForeground(new java.awt.Color(255, 255, 255));
        p7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p7.setText("Car 7");
        p7.setToolTipText("Car Parking Place 07");
        p7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p7.setOpaque(true);
        jPanel1.add(p7);
        p7.setBounds(850, 210, 140, 60);

        p6.setBackground(new java.awt.Color(0, 204, 102));
        p6.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p6.setForeground(new java.awt.Color(255, 255, 255));
        p6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p6.setText("Car 6");
        p6.setToolTipText("Car Parking Place 06");
        p6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p6.setOpaque(true);
        jPanel1.add(p6);
        p6.setBounds(850, 320, 140, 60);

        p5.setBackground(new java.awt.Color(0, 204, 102));
        p5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p5.setForeground(new java.awt.Color(255, 255, 255));
        p5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p5.setText("Car 5");
        p5.setToolTipText("Car Parking Place 05");
        p5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p5.setOpaque(true);
        jPanel1.add(p5);
        p5.setBounds(850, 420, 140, 60);

        p27.setBackground(new java.awt.Color(0, 204, 102));
        p27.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p27.setForeground(new java.awt.Color(255, 255, 255));
        p27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p27.setText("Bus 27");
        p27.setToolTipText("Bus Parking Place 06");
        p27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p27.setOpaque(true);
        p27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p27MouseExited(evt);
            }
        });
        jPanel1.add(p27);
        p27.setBounds(10, 500, 170, 60);

        p26.setBackground(new java.awt.Color(0, 204, 102));
        p26.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p26.setForeground(new java.awt.Color(255, 255, 255));
        p26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p26.setText("Bus 26");
        p26.setToolTipText("Bus Parking Place 05");
        p26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p26.setOpaque(true);
        p26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p26MouseExited(evt);
            }
        });
        jPanel1.add(p26);
        p26.setBounds(10, 420, 170, 60);

        p25.setBackground(new java.awt.Color(0, 204, 102));
        p25.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p25.setForeground(new java.awt.Color(255, 255, 255));
        p25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p25.setText("Bus 25");
        p25.setToolTipText("Bus Parking Place 04");
        p25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p25.setOpaque(true);
        p25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p25MouseExited(evt);
            }
        });
        jPanel1.add(p25);
        p25.setBounds(10, 340, 170, 60);

        p24.setBackground(new java.awt.Color(0, 204, 102));
        p24.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p24.setForeground(new java.awt.Color(255, 255, 255));
        p24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p24.setText("Bus 24");
        p24.setToolTipText("Bus Parking Place 03");
        p24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p24.setOpaque(true);
        p24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p24MouseExited(evt);
            }
        });
        jPanel1.add(p24);
        p24.setBounds(10, 260, 170, 60);

        p12.setBackground(new java.awt.Color(0, 204, 102));
        p12.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p12.setForeground(new java.awt.Color(255, 255, 255));
        p12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p12.setText("Car 12");
        p12.setToolTipText("Car Parking Place 12");
        p12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p12.setOpaque(true);
        jPanel1.add(p12);
        p12.setBounds(660, 210, 140, 60);

        p9.setBackground(new java.awt.Color(0, 204, 102));
        p9.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p9.setForeground(new java.awt.Color(255, 255, 255));
        p9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p9.setText("Car 9");
        p9.setToolTipText("Car Parking Place 09");
        p9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p9.setOpaque(true);
        jPanel1.add(p9);
        p9.setBounds(850, 0, 140, 60);

        p14.setBackground(new java.awt.Color(0, 204, 102));
        p14.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p14.setForeground(new java.awt.Color(255, 255, 255));
        p14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p14.setText("Car 14");
        p14.setToolTipText("Car Parking Place 14");
        p14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p14.setOpaque(true);
        jPanel1.add(p14);
        p14.setBounds(660, 0, 140, 60);

        p18.setBackground(new java.awt.Color(0, 204, 102));
        p18.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p18.setForeground(new java.awt.Color(255, 255, 255));
        p18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p18.setText("Car 18");
        p18.setToolTipText("Car Parking Place 18");
        p18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p18.setOpaque(true);
        jPanel1.add(p18);
        p18.setBounds(480, 0, 140, 60);

        p8.setBackground(new java.awt.Color(0, 204, 102));
        p8.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p8.setForeground(new java.awt.Color(255, 255, 255));
        p8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p8.setText("Car 8");
        p8.setToolTipText("Car Parking Place 08");
        p8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p8.setOpaque(true);
        jPanel1.add(p8);
        p8.setBounds(850, 100, 140, 60);

        p13.setBackground(new java.awt.Color(0, 204, 102));
        p13.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p13.setForeground(new java.awt.Color(255, 255, 255));
        p13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p13.setText("Car 13");
        p13.setToolTipText("Car Parking Place 13");
        p13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p13.setOpaque(true);
        jPanel1.add(p13);
        p13.setBounds(660, 100, 140, 60);

        p17.setBackground(new java.awt.Color(0, 204, 102));
        p17.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p17.setForeground(new java.awt.Color(255, 255, 255));
        p17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p17.setText("Car 17");
        p17.setToolTipText("Car Parking Place 17");
        p17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p17.setOpaque(true);
        jPanel1.add(p17);
        p17.setBounds(480, 100, 140, 60);

        p20.setBackground(new java.awt.Color(0, 204, 102));
        p20.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p20.setForeground(new java.awt.Color(255, 255, 255));
        p20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p20.setText("Car 20");
        p20.setToolTipText("Car Parking Place 20");
        p20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p20.setOpaque(true);
        jPanel1.add(p20);
        p20.setBounds(310, 100, 140, 60);

        p10.setBackground(new java.awt.Color(0, 204, 102));
        p10.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p10.setForeground(new java.awt.Color(255, 255, 255));
        p10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p10.setText("Car 10");
        p10.setToolTipText("Car Parking Place 10");
        p10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p10.setOpaque(true);
        jPanel1.add(p10);
        p10.setBounds(660, 420, 140, 60);

        p16.setBackground(new java.awt.Color(0, 204, 102));
        p16.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p16.setForeground(new java.awt.Color(255, 255, 255));
        p16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p16.setText("Car 16");
        p16.setToolTipText("Car Parking Place 16");
        p16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p16.setOpaque(true);
        jPanel1.add(p16);
        p16.setBounds(480, 210, 140, 60);

        p19.setBackground(new java.awt.Color(0, 204, 102));
        p19.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p19.setForeground(new java.awt.Color(255, 255, 255));
        p19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p19.setText("Car 19");
        p19.setToolTipText("Car Parking Place 19");
        p19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p19.setOpaque(true);
        jPanel1.add(p19);
        p19.setBounds(310, 210, 140, 60);

        p11.setBackground(new java.awt.Color(0, 204, 102));
        p11.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p11.setForeground(new java.awt.Color(255, 255, 255));
        p11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p11.setText("Car 11");
        p11.setToolTipText("Car Parking Place 11");
        p11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p11.setOpaque(true);
        jPanel1.add(p11);
        p11.setBounds(660, 320, 140, 60);

        p15.setBackground(new java.awt.Color(0, 204, 102));
        p15.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p15.setForeground(new java.awt.Color(255, 255, 255));
        p15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p15.setText("Car 15");
        p15.setToolTipText("Car Parking Place 15");
        p15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p15.setOpaque(true);
        jPanel1.add(p15);
        p15.setBounds(480, 320, 140, 60);

        p23.setBackground(new java.awt.Color(0, 204, 102));
        p23.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        p23.setForeground(new java.awt.Color(255, 255, 255));
        p23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p23.setText("Bus 23");
        p23.setToolTipText("Bus Parking Place 02");
        p23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p23.setOpaque(true);
        p23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p23MouseExited(evt);
            }
        });
        jPanel1.add(p23);
        p23.setBounds(10, 180, 170, 60);

        libMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/reserve/RS.png"))); // NOI18N
        libMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel1.add(libMain);
        libMain.setBounds(0, 0, 1202, 575);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p21MouseClicked
        GetDetailReserve detailReserve = new GetDetailReserve();
        detailReserve.setVisible(true);
        detailReserve.setPlaceID("p_21");
        this.dispose();
    }//GEN-LAST:event_p21MouseClicked

    private void p22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p22MouseEntered

    }//GEN-LAST:event_p22MouseEntered

    private void p22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p22MouseExited

    }//GEN-LAST:event_p22MouseExited

    private void p23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p23MouseEntered

    }//GEN-LAST:event_p23MouseEntered

    private void p23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p23MouseExited

    }//GEN-LAST:event_p23MouseExited

    private void p24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p24MouseExited

    }//GEN-LAST:event_p24MouseExited

    private void p24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p24MouseEntered

    }//GEN-LAST:event_p24MouseEntered

    private void p25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p25MouseExited

    }//GEN-LAST:event_p25MouseExited

    private void p25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p25MouseEntered

    }//GEN-LAST:event_p25MouseEntered

    private void p26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p26MouseExited

    }//GEN-LAST:event_p26MouseExited

    private void p26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p26MouseEntered

    }//GEN-LAST:event_p26MouseEntered

    private void p27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p27MouseExited

    }//GEN-LAST:event_p27MouseExited

    private void p27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p27MouseEntered

    }//GEN-LAST:event_p27MouseEntered

    private void p21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p21MouseExited

    }//GEN-LAST:event_p21MouseExited

    private void p21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p21MouseEntered

    }//GEN-LAST:event_p21MouseEntered

    private void p1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseExited

    }//GEN-LAST:event_p1MouseExited

    private void p1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseEntered

    }//GEN-LAST:event_p1MouseEntered

    private void libHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libHomeMouseClicked

    }//GEN-LAST:event_libHomeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setReservPlace();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservePlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservePlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservePlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservePlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservePlace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel libHome;
    private javax.swing.JLabel libMain;
    public javax.swing.JLabel p1;
    public javax.swing.JLabel p10;
    public javax.swing.JLabel p11;
    public javax.swing.JLabel p12;
    public javax.swing.JLabel p13;
    public javax.swing.JLabel p14;
    public javax.swing.JLabel p15;
    public javax.swing.JLabel p16;
    public javax.swing.JLabel p17;
    public javax.swing.JLabel p18;
    public javax.swing.JLabel p19;
    public javax.swing.JLabel p2;
    public javax.swing.JLabel p20;
    public javax.swing.JLabel p21;
    public javax.swing.JLabel p22;
    public javax.swing.JLabel p23;
    public javax.swing.JLabel p24;
    public javax.swing.JLabel p25;
    public javax.swing.JLabel p26;
    public javax.swing.JLabel p27;
    public javax.swing.JLabel p3;
    public javax.swing.JLabel p4;
    public javax.swing.JLabel p5;
    public javax.swing.JLabel p6;
    public javax.swing.JLabel p7;
    public javax.swing.JLabel p8;
    public javax.swing.JLabel p9;
    // End of variables declaration//GEN-END:variables

    private void setReservPlace() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String format = dateFormat.format(date);
        try {
            CustomerParkingController customerParkingController = ServerConnector.getServerConnector().getCustomerParkingController();
            ArrayList<CustomerParking> allCustomerParking = customerParkingController.getAllCustomerParking();
            for (CustomerParking customerParking : allCustomerParking) {
                if (customerParking != null) {
                    if (customerParking.getDate().equals(format)) {
                        String placeId = customerParking.getPlaceId();
                        String[] split = placeId.split("_");
                        switch (split[1]) {
                            case "1":
                                p1.setEnabled(false);
                                p1.setBackground(Color.red);
                                continue;
                            case "2":
                                p2.setEnabled(false);
                                p2.setBackground(Color.red);
                                continue;
                            case "3":
                                p3.setEnabled(false);
                                p3.setBackground(Color.red);
                                continue;
                            case "4":
                                p4.setEnabled(false);
                                p4.setBackground(Color.red);
                                continue;
                            case "5":
                                p5.setEnabled(false);
                                p5.setBackground(Color.red);
                                continue;
                            case "6":
                                p6.setEnabled(false);
                                p6.setBackground(Color.red);
                                continue;
                            case "7":
                                p7.setEnabled(false);
                                p7.setBackground(Color.red);
                                continue;
                            case "8":
                                p8.setEnabled(false);
                                p8.setBackground(Color.red);
                                continue;
                            case "9":
                                p9.setEnabled(false);
                                p9.setBackground(Color.red);
                                continue;
                            case "10":
                                p10.setEnabled(false);
                                p10.setBackground(Color.red);
                                continue;
                            case "11":
                                p11.setEnabled(false);
                                p11.setBackground(Color.red);
                                continue;
                            case "12":
                                p12.setEnabled(false);
                                p12.setBackground(Color.red);
                                continue;
                            case "13":
                                p13.setEnabled(false);
                                p13.setBackground(Color.red);
                                continue;
                            case "14":
                                p14.setEnabled(false);
                                p14.setBackground(Color.red);
                                continue;
                            case "15":
                                p15.setEnabled(false);
                                p15.setBackground(Color.red);
                                continue;
                            case "16":
                                p16.setEnabled(false);
                                p16.setBackground(Color.red);
                                continue;
                            case "17":
                                p17.setEnabled(false);
                                p17.setBackground(Color.red);
                                continue;
                            case "18":
                                p18.setEnabled(false);
                                p18.setBackground(Color.red);
                                continue;
                            case "19":
                                p19.setEnabled(false);
                                p19.setBackground(Color.red);
                                continue;
                            case "20":
                                p20.setEnabled(false);
                                p20.setBackground(Color.red);
                                continue;
                            case "21":
                                p21.setEnabled(false);
                                p21.setBackground(Color.red);
                                continue;
                            case "22":
                                p22.setEnabled(false);
                                p22.setBackground(Color.red);
                                continue;
                            case "23":
                                p23.setEnabled(false);
                                p23.setBackground(Color.red);
                                continue;
                            case "24":
                                p24.setEnabled(false);
                                p24.setBackground(Color.red);
                                continue;
                            case "25":
                                p25.setEnabled(false);
                                p25.setBackground(Color.red);
                                continue;
                            case "26":
                                p26.setEnabled(false);
                                p26.setBackground(Color.red);
                                continue;
                            case "27":
                                p27.setEnabled(false);
                                p27.setBackground(Color.red);
                        }
                    }
                }
            }

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {

        } catch (ClassNotFoundException | IOException ex) {

        }
    }
}
