/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.cmjd.example.com.smsccp.view.getdetail;

import edu.ijse.cmjd.example.com.smsccp.serverconnector.ServerConnector;
import edu.ijse.cmjd.example.com.smsccp.controller.CustomerController;
import edu.ijse.cmjd.example.com.smsccp.controller.CustomerParkingController;
import edu.ijse.cmjd.example.com.smsccp.controller.FixCustomerController;
import edu.ijse.cmjd.example.com.smsccp.controller.PlaceController;
import edu.ijse.cmjd.example.com.smsccp.model.Customer;
import edu.ijse.cmjd.example.com.smsccp.model.CustomerParking;
import edu.ijse.cmjd.example.com.smsccp.model.FixCustomer;
import edu.ijse.cmjd.example.com.smsccp.validate.Validate;
import edu.ijse.cmjd.example.com.smsccp.view.reserve.ReservePlace;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class GetDetailReserve extends javax.swing.JFrame {


    /**
     * Creates new form GetDetailReserve
     */
    public GetDetailReserve() {
        initComponents();
        setLocationRelativeTo(null);
        setDate();
        setTime();
        txtCustomerNicNo.requestFocus();
        libDone.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        libTitle = new javax.swing.JLabel();
        libPlaceId = new javax.swing.JLabel();
        libCustomerNIC = new javax.swing.JLabel();
        libCustomerName = new javax.swing.JLabel();
        libCustomerVehicalNo = new javax.swing.JLabel();
        libCustomerTele = new javax.swing.JLabel();
        libDate = new javax.swing.JLabel();
        libTime = new javax.swing.JLabel();
        txtPlaceId = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtVehicalNo = new javax.swing.JTextField();
        txtCustomerNicNo = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerTelephone = new javax.swing.JTextField();
        libDone = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        libSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panMain.setBackground(new java.awt.Color(153, 153, 153));
        panMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        panMain.setMaximumSize(new java.awt.Dimension(519, 351));
        panMain.setMinimumSize(new java.awt.Dimension(519, 351));
        panMain.setLayout(null);

        libTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        libTitle.setForeground(new java.awt.Color(243, 243, 243));
        libTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libTitle.setText("Input Your Details");
        panMain.add(libTitle);
        libTitle.setBounds(160, 10, 340, 50);

        libPlaceId.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        libPlaceId.setForeground(new java.awt.Color(243, 243, 243));
        libPlaceId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        libPlaceId.setText("Your Parking Place ID  : ");
        panMain.add(libPlaceId);
        libPlaceId.setBounds(50, 130, 200, 30);

        libCustomerNIC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        libCustomerNIC.setForeground(new java.awt.Color(243, 243, 243));
        libCustomerNIC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        libCustomerNIC.setText("Your NIC No  : ");
        panMain.add(libCustomerNIC);
        libCustomerNIC.setBounds(50, 170, 200, 30);

        libCustomerName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        libCustomerName.setForeground(new java.awt.Color(243, 243, 243));
        libCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        libCustomerName.setText("Your Name  : ");
        panMain.add(libCustomerName);
        libCustomerName.setBounds(50, 210, 200, 30);

        libCustomerVehicalNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        libCustomerVehicalNo.setForeground(new java.awt.Color(243, 243, 243));
        libCustomerVehicalNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        libCustomerVehicalNo.setText("Your Vehical No  : ");
        panMain.add(libCustomerVehicalNo);
        libCustomerVehicalNo.setBounds(50, 290, 200, 30);

        libCustomerTele.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        libCustomerTele.setForeground(new java.awt.Color(243, 243, 243));
        libCustomerTele.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        libCustomerTele.setText("Your Telephone No  : ");
        panMain.add(libCustomerTele);
        libCustomerTele.setBounds(50, 250, 200, 30);

        libDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        libDate.setForeground(new java.awt.Color(243, 243, 243));
        libDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        libDate.setText("Date : ");
        panMain.add(libDate);
        libDate.setBounds(60, 70, 60, 30);

        libTime.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        libTime.setForeground(new java.awt.Color(243, 243, 243));
        libTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        libTime.setText("Time : ");
        panMain.add(libTime);
        libTime.setBounds(490, 70, 60, 30);

        txtPlaceId.setEditable(false);
        txtPlaceId.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtPlaceId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPlaceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaceIdActionPerformed(evt);
            }
        });
        panMain.add(txtPlaceId);
        txtPlaceId.setBounds(250, 130, 110, 30);

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panMain.add(txtDate);
        txtDate.setBounds(120, 70, 100, 30);

        txtTime.setEditable(false);
        txtTime.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        panMain.add(txtTime);
        txtTime.setBounds(550, 70, 90, 30);

        txtVehicalNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtVehicalNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtVehicalNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicalNoActionPerformed(evt);
            }
        });
        panMain.add(txtVehicalNo);
        txtVehicalNo.setBounds(250, 290, 220, 30);

        txtCustomerNicNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCustomerNicNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCustomerNicNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNicNoActionPerformed(evt);
            }
        });
        txtCustomerNicNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerNicNoKeyPressed(evt);
            }
        });
        panMain.add(txtCustomerNicNo);
        txtCustomerNicNo.setBounds(250, 170, 220, 30);

        txtCustomerName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCustomerName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        panMain.add(txtCustomerName);
        txtCustomerName.setBounds(250, 210, 220, 30);

        txtCustomerTelephone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCustomerTelephone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCustomerTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerTelephoneActionPerformed(evt);
            }
        });
        txtCustomerTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerTelephoneKeyPressed(evt);
            }
        });
        panMain.add(txtCustomerTelephone);
        txtCustomerTelephone.setBounds(250, 250, 220, 30);

        libDone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/done2.png"))); // NOI18N
        libDone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libDoneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libDoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libDoneMouseExited(evt);
            }
        });
        panMain.add(libDone);
        libDone.setBounds(470, 330, 180, 90);

        btExit.setBackground(new java.awt.Color(153, 0, 0));
        btExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("X");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        panMain.add(btExit);
        btExit.setBounds(603, 5, 45, 30);

        Panel1.setBackground(new java.awt.Color(0, 204, 204));
        Panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        panMain.add(Panel1);
        Panel1.setBounds(0, 0, 50, 423);

        libSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Search2.png"))); // NOI18N
        libSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libSearchMouseExited(evt);
            }
        });
        panMain.add(libSearch);
        libSearch.setBounds(480, 150, 140, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libDoneMouseClicked
        ReservPlace();
    }//GEN-LAST:event_libDoneMouseClicked

    private void txtPlaceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlaceIdActionPerformed

    private void txtVehicalNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicalNoActionPerformed
        libDone.setEnabled(true);
    }//GEN-LAST:event_txtVehicalNoActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        exitfrom();
    }//GEN-LAST:event_btExitActionPerformed

    private void txtCustomerNicNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNicNoActionPerformed
        txtCustomerName.requestFocus();
    }//GEN-LAST:event_txtCustomerNicNoActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        txtCustomerTelephone.requestFocus();
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCustomerTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerTelephoneActionPerformed
        txtVehicalNo.requestFocus();
    }//GEN-LAST:event_txtCustomerTelephoneActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        reservPlace();
    }//GEN-LAST:event_formWindowOpened

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void libDoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libDoneMouseExited
        libDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/done2.png")));
    }//GEN-LAST:event_libDoneMouseExited

    private void libDoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libDoneMouseEntered
        libDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/done1.png")));
    }//GEN-LAST:event_libDoneMouseEntered

    private void libSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libSearchMouseExited
        libSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Search2.png")));
    }//GEN-LAST:event_libSearchMouseExited

    private void libSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libSearchMouseEntered
        libSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Search1.png")));
    }//GEN-LAST:event_libSearchMouseEntered

    private void libSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libSearchMouseClicked
        searchFixCustomer();
    }//GEN-LAST:event_libSearchMouseClicked

    private void txtCustomerNicNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNicNoKeyPressed
        Validate.nicNoValidation(txtCustomerNicNo);
    }//GEN-LAST:event_txtCustomerNicNoKeyPressed

    private void txtCustomerTelephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerTelephoneKeyPressed
        Validate.tpNoValidation(txtCustomerTelephone);
    }//GEN-LAST:event_txtCustomerTelephoneKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetDetailReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetDetailReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetDetailReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetDetailReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btExit;
    private javax.swing.JLabel libCustomerNIC;
    private javax.swing.JLabel libCustomerName;
    private javax.swing.JLabel libCustomerTele;
    private javax.swing.JLabel libCustomerVehicalNo;
    private javax.swing.JLabel libDate;
    private javax.swing.JLabel libDone;
    private javax.swing.JLabel libPlaceId;
    private javax.swing.JLabel libSearch;
    private javax.swing.JLabel libTime;
    private javax.swing.JLabel libTitle;
    private javax.swing.JPanel panMain;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerNicNo;
    private javax.swing.JTextField txtCustomerTelephone;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPlaceId;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtVehicalNo;
    // End of variables declaration//GEN-END:variables

    private void ReservPlace() {
        try {
            CustomerParkingController customerParkingController = ServerConnector.getServerConnector().getCustomerParkingController();
            PlaceController placeController = ServerConnector.getServerConnector().getPlaceController();
            CustomerController customerController = ServerConnector.getServerConnector().getCustomerController();

            Customer customer = new Customer(txtCustomerName.getText(), txtCustomerNicNo.getText(), txtCustomerTelephone.getText(), txtVehicalNo.getText());
            CustomerParking parking = new CustomerParking(txtPlaceId.getText(), txtCustomerNicNo.getText(), txtDate.getText(), txtTime.getText(), null);
            boolean addCustomer = customerController.addCustomer(customer);

            if (addCustomer) {
                boolean addCustomerParking = customerParkingController.addCustomerParking(parking);

                if (addCustomerParking) {
                    JOptionPane.showMessageDialog(null, "Place Reserve Success !!!");
                    new ReservePlace().setVisible(true);
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Place Reserve Fail !!!");
//                    this.reservePlace.reservSuccess(false);
//                    this.reservePlace.setVisible(false);
                    //setVisible(false);
                }
                placeController.releasePlace(txtPlaceId.getText());
            }

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {

        } catch (ClassNotFoundException | IOException ex) {

        }
    }

    private void setDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String format = dateFormat.format(date);
        txtDate.setText(format);
    }

    private void setTime() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    Date time = new Date();
                    SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss");
                    String format = timeFormat.format(time);
                    txtTime.setText(format);
                }
            }
        }.start();
    }

    public void setPlaceID(String place) {
        txtPlaceId.setText(place);
    }

    private void reservPlace() {
        try {
            PlaceController placeController = ServerConnector.getServerConnector().getPlaceController();
            placeController.reservePlace(txtPlaceId.getText());
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(GetDetailReserve.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GetDetailReserve.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void exitfrom() {
        new ReservePlace().setVisible(true);
        this.dispose();
    }

    private void searchFixCustomer() {
        try {
            FixCustomerController fixCustomerController = ServerConnector.getServerConnector().getFixCustomerController();
            FixCustomer searchFixCustomer = fixCustomerController.searchFixCustomer(txtCustomerNicNo.getText());
            if (searchFixCustomer != null) {
                txtCustomerName.setText(searchFixCustomer.getFxCustomerName());
                txtCustomerTelephone.setText(searchFixCustomer.getFxCustomerTelephone());
                txtVehicalNo.requestFocus();
            } else {
                //jop
            }
            
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(GetDetailReserve.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(GetDetailReserve.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
