package edu.ijse.cmjd.smsccp.view;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
public class HomePage extends JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setLocationRelativeTo(null);
        setDate();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        libDate = new javax.swing.JLabel();
        libTime = new javax.swing.JLabel();
        libReservePlace = new javax.swing.JLabel();
        libReleasePlace = new javax.swing.JLabel();
        libBusinessDetails = new javax.swing.JLabel();
        libDataInput = new javax.swing.JLabel();
        libLogOut = new javax.swing.JLabel();
        libTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panMain.setBackground(new java.awt.Color(153, 153, 153));
        panMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        panMain.setMaximumSize(new java.awt.Dimension(616, 490));
        panMain.setMinimumSize(new java.awt.Dimension(616, 490));
        panMain.setPreferredSize(new java.awt.Dimension(616, 490));
        panMain.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        panMain.add(jPanel1);
        jPanel1.setBounds(0, 0, 40, 490);

        libDate.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        libDate.setForeground(new java.awt.Color(255, 255, 255));
        libDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        panMain.add(libDate);
        libDate.setBounds(50, 50, 130, 30);

        libTime.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        libTime.setForeground(new java.awt.Color(255, 255, 255));
        libTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libTime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        panMain.add(libTime);
        libTime.setBounds(50, 10, 130, 30);

        libReservePlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libReservePlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btReserve2.png"))); // NOI18N
        libReservePlace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libReservePlace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libReservePlaceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libReservePlaceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libReservePlaceMouseExited(evt);
            }
        });
        panMain.add(libReservePlace);
        libReservePlace.setBounds(60, 110, 350, 170);

        libReleasePlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btRelease2.png"))); // NOI18N
        libReleasePlace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libReleasePlace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libReleasePlaceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libReleasePlaceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libReleasePlaceMouseExited(evt);
            }
        });
        panMain.add(libReleasePlace);
        libReleasePlace.setBounds(420, 110, 238, 170);

        libBusinessDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libBusinessDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btDetails2.png"))); // NOI18N
        libBusinessDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libBusinessDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libBusinessDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libBusinessDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libBusinessDetailsMouseExited(evt);
            }
        });
        panMain.add(libBusinessDetails);
        libBusinessDetails.setBounds(60, 290, 260, 190);

        libDataInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libDataInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btData2.png"))); // NOI18N
        libDataInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libDataInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libDataInputMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libDataInputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libDataInputMouseExited(evt);
            }
        });
        panMain.add(libDataInput);
        libDataInput.setBounds(330, 290, 200, 190);

        libLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btLogOut2.png"))); // NOI18N
        libLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libLogOutMouseExited(evt);
            }
        });
        panMain.add(libLogOut);
        libLogOut.setBounds(540, 290, 130, 190);

        libTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        libTitle.setForeground(new java.awt.Color(255, 255, 255));
        libTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libTitle.setText("SMS Car Park Manage System");
        panMain.add(libTitle);
        libTitle.setBounds(180, 20, 500, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libReservePlaceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libReservePlaceMouseEntered
        libReservePlace.setIcon(new ImageIcon(getClass().getResource("/com/smsccp/img/home/btReserve1.png")));
    }//GEN-LAST:event_libReservePlaceMouseEntered

    private void libReservePlaceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libReservePlaceMouseExited
        libReservePlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btReserve2.png")));
    }//GEN-LAST:event_libReservePlaceMouseExited

    private void libReservePlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libReservePlaceMouseClicked
        new ReservePlace().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_libReservePlaceMouseClicked

    private void libReleasePlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libReleasePlaceMouseClicked
        new ReleasePlace().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_libReleasePlaceMouseClicked

    private void libReleasePlaceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libReleasePlaceMouseEntered
        libReleasePlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btRelease1.png")));
    }//GEN-LAST:event_libReleasePlaceMouseEntered

    private void libReleasePlaceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libReleasePlaceMouseExited
        libReleasePlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btRelease2.png")));
    }//GEN-LAST:event_libReleasePlaceMouseExited

    private void libBusinessDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libBusinessDetailsMouseClicked
        new DataView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_libBusinessDetailsMouseClicked

    private void libBusinessDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libBusinessDetailsMouseEntered
        libBusinessDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btDetails1.png")));
    }//GEN-LAST:event_libBusinessDetailsMouseEntered

    private void libBusinessDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libBusinessDetailsMouseExited
        libBusinessDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btDetails2.png")));
    }//GEN-LAST:event_libBusinessDetailsMouseExited

    private void libDataInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libDataInputMouseClicked
        new InputMenu(this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_libDataInputMouseClicked

    private void libDataInputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libDataInputMouseEntered
        libDataInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btData1.png")));
    }//GEN-LAST:event_libDataInputMouseEntered

    private void libDataInputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libDataInputMouseExited
        libDataInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btData2.png")));
    }//GEN-LAST:event_libDataInputMouseExited

    private void libLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libLogOutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_libLogOutMouseClicked

    private void libLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libLogOutMouseEntered
        libLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btLogOut1.png")));
    }//GEN-LAST:event_libLogOutMouseEntered

    private void libLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libLogOutMouseExited
        libLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/home/btLogOut2.png")));
    }//GEN-LAST:event_libLogOutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel libBusinessDetails;
    private javax.swing.JLabel libDataInput;
    private javax.swing.JLabel libDate;
    private javax.swing.JLabel libLogOut;
    private javax.swing.JLabel libReleasePlace;
    private javax.swing.JLabel libReservePlace;
    private javax.swing.JLabel libTime;
    private javax.swing.JLabel libTitle;
    private javax.swing.JPanel panMain;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date date = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        libDate.setText(format.format(date));
    }

    private void setTime() {
        new Thread() {
            public void run() {
                while (true) {                    
                    Date date = new Date();
                    SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss");
                    libTime.setText(format.format(date));
                }
            }
        }.start();
    }
}
