/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.cmjd.smsccp.view;

import edu.ijse.cmjd.smsccp.serverconnector.ServerConnector;
import edu.ijse.cmjd.smsccp.controller.JobroleController;
import edu.ijse.cmjd.smsccp.model.JobRole;
import edu.ijse.cmjd.smsccp.validate.Validate;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author U s E r™
 */
public class inputJobRole extends javax.swing.JDialog {

    private final DefaultTableModel tableModel;
    private InputCustomers inputCustomers;

    /**
     * Creates new form inputJobRole
     */
    public inputJobRole(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inputCustomers = (InputCustomers) parent;
        tableModel = (DefaultTableModel) tabJobroleinfo.getModel();
        txtSearch.setText("Enter Jobrole Name to Search");
        libRemove.setEnabled(false);
        libUpbate.setEnabled(false);
        loadJobrole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btExit = new javax.swing.JButton();
        libTitle = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        libSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabJobroleinfo = new javax.swing.JTable();
        libJobroleName = new javax.swing.JLabel();
        libInsertDate = new javax.swing.JLabel();
        txtJobrole = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        libInput = new javax.swing.JLabel();
        libUpbate = new javax.swing.JLabel();
        libRemove = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 50, 553);

        btExit.setBackground(new java.awt.Color(153, 0, 0));
        btExit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("X");
        btExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        jPanel1.add(btExit);
        btExit.setBounds(764, 5, 45, 27);

        libTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        libTitle.setForeground(new java.awt.Color(255, 255, 255));
        libTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libTitle.setText("Jobrole Data");
        jPanel1.add(libTitle);
        libTitle.setBounds(280, 10, 280, 42);

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        jPanel1.add(txtSearch);
        txtSearch.setBounds(260, 80, 320, 30);

        libSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Search2.png"))); // NOI18N
        libSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libSearchMouseExited(evt);
            }
        });
        jPanel1.add(libSearch);
        libSearch.setBounds(590, 65, 140, 50);

        tabJobroleinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jobrole Name", "Insert Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabJobroleinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabJobroleinfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabJobroleinfo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 120, 700, 190);

        libJobroleName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        libJobroleName.setForeground(new java.awt.Color(255, 255, 255));
        libJobroleName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        libJobroleName.setText("Jobrole Name : ");
        jPanel1.add(libJobroleName);
        libJobroleName.setBounds(80, 350, 140, 30);

        libInsertDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        libInsertDate.setForeground(new java.awt.Color(255, 255, 255));
        libInsertDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        libInsertDate.setText("Insert Date : ");
        jPanel1.add(libInsertDate);
        libInsertDate.setBounds(80, 400, 140, 30);

        txtJobrole.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtJobrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobroleActionPerformed(evt);
            }
        });
        jPanel1.add(txtJobrole);
        txtJobrole.setBounds(230, 350, 310, 30);

        txtDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDateKeyReleased(evt);
            }
        });
        jPanel1.add(txtDate);
        txtDate.setBounds(230, 400, 220, 30);

        libInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Input2.png"))); // NOI18N
        libInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libInputMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libInputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libInputMouseExited(evt);
            }
        });
        jPanel1.add(libInput);
        libInput.setBounds(180, 450, 170, 90);

        libUpbate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libUpbate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Update2.png"))); // NOI18N
        libUpbate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libUpbate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libUpbateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libUpbateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libUpbateMouseExited(evt);
            }
        });
        jPanel1.add(libUpbate);
        libUpbate.setBounds(360, 450, 170, 90);

        libRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Remove2.png"))); // NOI18N
        libRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libRemoveMouseExited(evt);
            }
        });
        jPanel1.add(libRemove);
        libRemove.setBounds(540, 450, 164, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libSearchMouseExited
        libSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Search2.png")));
    }//GEN-LAST:event_libSearchMouseExited

    private void libSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libSearchMouseEntered
        libSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Search1.png")));
    }//GEN-LAST:event_libSearchMouseEntered

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        txtSearch.setText("Enter Jobrole Name to Search");
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtJobroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobroleActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void libInputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libInputMouseEntered
        libInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Input1.png")));
    }//GEN-LAST:event_libInputMouseEntered

    private void libInputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libInputMouseExited
        libInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Input2.png")));
    }//GEN-LAST:event_libInputMouseExited

    private void libUpbateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libUpbateMouseEntered
        libUpbate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Update1.png")));
    }//GEN-LAST:event_libUpbateMouseEntered

    private void libUpbateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libUpbateMouseExited
        libUpbate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Update2.png")));
    }//GEN-LAST:event_libUpbateMouseExited

    private void libRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libRemoveMouseEntered
        libRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Remove1.png")));
    }//GEN-LAST:event_libRemoveMouseEntered

    private void libRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libRemoveMouseExited
        libRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/from/Remove2.png")));
    }//GEN-LAST:event_libRemoveMouseExited

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btExitActionPerformed

    private void tabJobroleinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabJobroleinfoMouseClicked
        setValuesToTextFeilds();
    }//GEN-LAST:event_tabJobroleinfoMouseClicked

    private void libInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libInputMouseClicked
        InputNewJobrole();
    }//GEN-LAST:event_libInputMouseClicked

    private void libUpbateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libUpbateMouseClicked
        UpdateJobrole();
    }//GEN-LAST:event_libUpbateMouseClicked

    private void libRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libRemoveMouseClicked
        RemoveJobrole();
    }//GEN-LAST:event_libRemoveMouseClicked

    private void txtDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyReleased
        Validate.dateValidation(txtDate);
    }//GEN-LAST:event_txtDateKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputJobRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputJobRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputJobRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputJobRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                inputJobRole dialog = new inputJobRole(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel libInput;
    private javax.swing.JLabel libInsertDate;
    private javax.swing.JLabel libJobroleName;
    private javax.swing.JLabel libRemove;
    private javax.swing.JLabel libSearch;
    private javax.swing.JLabel libTitle;
    private javax.swing.JLabel libUpbate;
    private javax.swing.JTable tabJobroleinfo;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtJobrole;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadJobrole() {
        try {
            JobroleController jobroleController = ServerConnector.getServerConnector().getJobroleController();
            ArrayList<JobRole> allJobRole = jobroleController.getAllJobRole();
            tableModel.setRowCount(0);
            if (!allJobRole.isEmpty()) {
                for (JobRole jobRole : allJobRole) {
                    Object[] row = {jobRole.getJobRoleName(), jobRole.getDate()};
                    tableModel.addRow(row);
                }
            } else {
                Object[] row = {"No Jobroles", "No Jobroles"};
                tableModel.addRow(row);
            }

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            new ServerNull().setVisible(true);
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(inputJobRole.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setMessageForNewJobrole(String message) {
        loadJobrole();
        inputCustomers.loadJobRoles();
    }

    private void setValuesToTextFeilds() {
        try {
            int selectedRow = tabJobroleinfo.getSelectedRow();
            String jobrole = String.valueOf(tabJobroleinfo.getValueAt(selectedRow, 0));
            String date = String.valueOf(tabJobroleinfo.getValueAt(selectedRow, 1));
            JobroleController jobroleController = ServerConnector.getServerConnector().getJobroleController();
            boolean isreleaseJobrole = jobroleController.releaseJobrole(txtJobrole.getText());
            if (isreleaseJobrole) {
                boolean isreserveJobrole = jobroleController.reserveJobrole(jobrole);
                if (isreserveJobrole) {
                    txtDate.setText(date);
                    txtJobrole.setText(jobrole);
                } else {
                    JOptionPane.showMessageDialog(null, "Error in Customer Reserv !!!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error in Customer Release !!!");
            }
            
            libRemove.setEnabled(true);
            libUpbate.setEnabled(true);
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            new ServerNull().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(inputJobRole.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void InputNewJobrole() {
        try {
            JobroleController jobroleController = ServerConnector.getServerConnector().getJobroleController();
            JobRole jobRole = new JobRole(txtJobrole.getText(), txtDate.getText());
            boolean isaddJobRole = jobroleController.addJobRole(jobRole);
            if (isaddJobRole) {
                JOptionPane.showMessageDialog(null, "Jobrole Successfully Input !!!");
            } else {
                JOptionPane.showMessageDialog(null, "Jobrole Input fail !!!");
            }

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            new ServerNull().setVisible(true);
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(inputJobRole.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void UpdateJobrole() {
        try {
            Object[] objects = {"Change","Cancel"};
            int showOptionDialog = JOptionPane.showOptionDialog(this, "You want to change date to Today !!!", "Qustion", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, objects, objects[0]);
            JobroleController jobroleController = ServerConnector.getServerConnector().getJobroleController();
            
            if (showOptionDialog == 0) {
                Date date = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String format = dateFormat.format(date);
                
                JobRole jobRole = new JobRole(txtJobrole.getText(), format);
                boolean isupdateJobRole = jobroleController.updateJobRole(jobRole);
                if (isupdateJobRole) {
                    JOptionPane.showMessageDialog(null, "Jobrole Successfully Update !!!");
                } else {
                    JOptionPane.showMessageDialog(null, "Jobrole Update fail !!!");
                }
                jobroleController.releaseJobrole(txtJobrole.getText());
                
            } else {
                JobRole jobRole = new JobRole(txtJobrole.getText(), txtDate.getText());
                boolean addJobRole = jobroleController.addJobRole(jobRole);
                if (addJobRole) {
                    JOptionPane.showMessageDialog(null, "Jobrole Successfully Update !!!");
                } else {
                    JOptionPane.showMessageDialog(null, "Jobrole Update fail !!!");
                }
                jobroleController.releaseJobrole(txtJobrole.getText());
            }
        } catch (NotBoundException | ClassNotFoundException | IOException ex) {
            Logger.getLogger(inputJobRole.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void RemoveJobrole() {
        try {
            JobroleController jobroleController = ServerConnector.getServerConnector().getJobroleController();
            boolean deleteJobRole = jobroleController.deleteJobRole(txtJobrole.getText());
            if (deleteJobRole) {
                JOptionPane.showMessageDialog(null, "Jobrole Successfully Delete !!!");
            } else {
                JOptionPane.showMessageDialog(null, "Jobrole Delete fail !!!");
            }
            jobroleController.releaseJobrole(txtJobrole.getText());
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            new ServerNull().setVisible(true);
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(inputJobRole.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
