/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.ijse.cmjd.smsccp.view;

import edu.ijse.cmjd.smsccp.view.HomePage;
import java.awt.HeadlessException;

/**
 *
 * @author U s E r™
 */
public class InputMenu extends javax.swing.JFrame {
    private HomePage homePage;
    /**
     * Creates new form InputMenu
     */
    public InputMenu(HomePage homePage) {
        initComponents();
        this.homePage = homePage;
        setLocationRelativeTo(null);
    }

    public InputMenu(){
        initComponents();
        setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        libTitle = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        libNewUser = new javax.swing.JLabel();
        libNewCustomer = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        libNewPlace = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panMain.setBackground(new java.awt.Color(153, 153, 153));
        panMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        panMain.setLayout(null);

        libTitle.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        libTitle.setForeground(new java.awt.Color(255, 255, 255));
        libTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libTitle.setText("Select Your Input");
        panMain.add(libTitle);
        libTitle.setBounds(110, 0, 230, 40);

        btExit.setBackground(new java.awt.Color(153, 0, 0));
        btExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("X");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        panMain.add(btExit);
        btExit.setBounds(366, 5, 45, 29);

        libNewUser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        libNewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libNewUser.setText("Input New User");
        libNewUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        libNewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libNewUserMouseClicked(evt);
            }
        });
        panMain.add(libNewUser);
        libNewUser.setBounds(80, 270, 290, 50);

        libNewCustomer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        libNewCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libNewCustomer.setText("Input New Fix Customer");
        libNewCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        libNewCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libNewCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libNewCustomerMouseClicked(evt);
            }
        });
        panMain.add(libNewCustomer);
        libNewCustomer.setBounds(80, 70, 290, 50);

        Panel1.setBackground(new java.awt.Color(0, 204, 204));
        Panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        panMain.add(Panel1);
        Panel1.setBounds(0, 0, 50, 349);

        libNewPlace.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        libNewPlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libNewPlace.setText("Input New Parking Place");
        libNewPlace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        libNewPlace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libNewPlace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libNewPlaceMouseClicked(evt);
            }
        });
        panMain.add(libNewPlace);
        libNewPlace.setBounds(80, 170, 290, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        if (homePage != null) {
            homePage.setVisible(true);
            this.dispose();
        } else {
            new HomePage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btExitActionPerformed

    private void libNewCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libNewCustomerMouseClicked
        new InputCustomers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_libNewCustomerMouseClicked

    private void libNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libNewUserMouseClicked
        
    }//GEN-LAST:event_libNewUserMouseClicked

    private void libNewPlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libNewPlaceMouseClicked
        new InputPlace().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_libNewPlaceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btExit;
    private javax.swing.JLabel libNewCustomer;
    private javax.swing.JLabel libNewPlace;
    private javax.swing.JLabel libNewUser;
    private javax.swing.JLabel libTitle;
    private javax.swing.JPanel panMain;
    // End of variables declaration//GEN-END:variables
}
