/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.cmjd.smsccp.view;

import edu.ijse.cmjd.smsccp.controller.UserController;
import edu.ijse.cmjd.smsccp.model.Users;
import edu.ijse.cmjd.smsccp.serverconnector.ServerConnector;
import edu.ijse.cmjd.smsccp.view.HomePage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author U s E r™
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        txtUserName.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        Userimg = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        keyimg = new javax.swing.JLabel();
        LibLogIn = new javax.swing.JLabel();
        libLogInimg = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        libMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panMain.setMaximumSize(new java.awt.Dimension(464, 256));
        panMain.setMinimumSize(new java.awt.Dimension(464, 256));
        panMain.setPreferredSize(new java.awt.Dimension(464, 256));
        panMain.setLayout(null);

        txtUserName.setBorder(null);
        txtUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        panMain.add(txtUserName);
        txtUserName.setBounds(50, 98, 250, 30);

        Userimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Userimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/login/strudent s.png"))); // NOI18N
        panMain.add(Userimg);
        Userimg.setBounds(300, 90, 50, 50);

        txtPassword.setBorder(null);
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panMain.add(txtPassword);
        txtPassword.setBounds(50, 163, 250, 30);

        keyimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/login/key.png"))); // NOI18N
        panMain.add(keyimg);
        keyimg.setBounds(300, 160, 50, 40);

        LibLogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LibLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/login/lock.png"))); // NOI18N
        LibLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LibLogInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LibLogInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LibLogInMouseExited(evt);
            }
        });
        panMain.add(LibLogIn);
        LibLogIn.setBounds(370, 90, 80, 120);

        libLogInimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libLogInimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/login/btLogIn2.png"))); // NOI18N
        libLogInimg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libLogInimgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libLogInimgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libLogInimgMouseExited(evt);
            }
        });
        panMain.add(libLogInimg);
        libLogInimg.setBounds(370, 90, 80, 120);

        btExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("X");
        btExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btExit.setContentAreaFilled(false);
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        panMain.add(btExit);
        btExit.setBounds(2, 223, 30, 30);

        libMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/login/Login copy.png"))); // NOI18N
        libMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        panMain.add(libMain);
        libMain.setBounds(0, 0, 464, 255);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libLogInimgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libLogInimgMouseClicked

    }//GEN-LAST:event_libLogInimgMouseClicked

    private void libLogInimgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libLogInimgMouseEntered

    }//GEN-LAST:event_libLogInimgMouseEntered

    private void libLogInimgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libLogInimgMouseExited

    }//GEN-LAST:event_libLogInimgMouseExited

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        txtPassword.requestFocus();
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        checkpassword();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        checkServer();
    }//GEN-LAST:event_formWindowOpened

    private void LibLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibLogInMouseClicked
        checkpassword();
    }//GEN-LAST:event_LibLogInMouseClicked

    private void LibLogInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibLogInMouseExited
        libLogInimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/login/btLogIn2.png")));
    }//GEN-LAST:event_LibLogInMouseExited

    private void LibLogInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibLogInMouseEntered
        libLogInimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smsccp/img/login/btLogIn1.png")));
    }//GEN-LAST:event_LibLogInMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LibLogIn;
    private javax.swing.JLabel Userimg;
    private javax.swing.JButton btExit;
    private javax.swing.JLabel keyimg;
    private javax.swing.JLabel libLogInimg;
    private javax.swing.JLabel libMain;
    private javax.swing.JPanel panMain;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void checkServer() {
        try {
            ServerConnector serverConnector = ServerConnector.getServerConnector();
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            new ServerNull().setVisible(true);
            this.dispose();
            setVisible(false);
        }
    }

    private void checkpassword() {
        try {
            UserController userController = ServerConnector.getServerConnector().getUserController();
            Users searchUser = userController.searchUser(txtUserName.getText());
            if (searchUser != null) {
                if (searchUser.getUserPassword().equals(txtPassword.getText().toString())) {
                    new HomePage().setVisible(true);
                    this.dispose();
                } else if (txtUserName.getText().equals("") || txtPassword.getText().toString().equals("")) {
                    JOptionPane.showMessageDialog(this, "Yuor password or username invalid !!");
                } else {
                    JOptionPane.showMessageDialog(this, "Yuor password or username invalid !!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Yuor password or username invalid !!");
            }
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            new ServerNull().setVisible(true);
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
