/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.ijse.cmjd.smsccp.main;

/**
 *
 * @author U s E r™
 */
public class ServerStart extends javax.swing.JFrame {

    /**
     * Creates new form ServerStart
     */
    public ServerStart() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        libTitle = new javax.swing.JLabel();
        ScrollServerinfo = new javax.swing.JScrollPane();
        txtServerInfo = new javax.swing.JTextArea();
        btStartServer = new javax.swing.JButton();
        btminimeze = new javax.swing.JButton();
        btExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panMain.setBackground(new java.awt.Color(255, 255, 255));
        panMain.setMaximumSize(new java.awt.Dimension(569, 174));
        panMain.setMinimumSize(new java.awt.Dimension(569, 174));
        panMain.setPreferredSize(new java.awt.Dimension(569, 174));
        panMain.setLayout(null);

        libTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        libTitle.setForeground(new java.awt.Color(0, 102, 102));
        libTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libTitle.setText("Start Your Server");
        panMain.add(libTitle);
        libTitle.setBounds(220, 0, 260, 40);

        txtServerInfo.setEditable(false);
        txtServerInfo.setBackground(new java.awt.Color(102, 102, 102));
        txtServerInfo.setColumns(20);
        txtServerInfo.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        txtServerInfo.setForeground(new java.awt.Color(255, 255, 255));
        txtServerInfo.setRows(5);
        ScrollServerinfo.setViewportView(txtServerInfo);

        panMain.add(ScrollServerinfo);
        ScrollServerinfo.setBounds(20, 120, 600, 170);

        btStartServer.setBackground(new java.awt.Color(0, 51, 102));
        btStartServer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btStartServer.setForeground(new java.awt.Color(255, 255, 255));
        btStartServer.setText("Start");
        btStartServer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartServerActionPerformed(evt);
            }
        });
        panMain.add(btStartServer);
        btStartServer.setBounds(20, 60, 110, 40);

        btminimeze.setBackground(new java.awt.Color(0, 102, 153));
        btminimeze.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btminimeze.setForeground(new java.awt.Color(255, 255, 255));
        btminimeze.setText("_");
        btminimeze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btminimezeActionPerformed(evt);
            }
        });
        panMain.add(btminimeze);
        btminimeze.setBounds(558, 0, 45, 30);

        btExit.setBackground(new java.awt.Color(153, 0, 0));
        btExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("X");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        panMain.add(btExit);
        btExit.setBounds(603, 0, 45, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartServerActionPerformed
        boolean startServer = SMSCCarParkManage_Server.startServer();
        if (startServer) {
            txtServerInfo.setText("\tServer is running......\n\t\t ServerPort is"
                    + " : 5050\n\t\t Server name is : SMSCCP");
        } else {
            txtServerInfo.setText("\tServer is not running !!!! \n\t\t Plaese "
                    + "Restart Server...........");
        }
    }//GEN-LAST:event_btStartServerActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void btminimezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btminimezeActionPerformed
        this.setState(ServerStart.ICONIFIED);
    }//GEN-LAST:event_btminimezeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollServerinfo;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btStartServer;
    private javax.swing.JButton btminimeze;
    private javax.swing.JLabel libTitle;
    private javax.swing.JPanel panMain;
    private javax.swing.JTextArea txtServerInfo;
    // End of variables declaration//GEN-END:variables
}
